# Generated by Django 5.1.2 on 2025-05-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0041_merge_20250509_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='uses_type',
            field=models.CharField(blank=True, choices=[('PER_DAY', 'X/Day'), ('RECHARGE_ON_ROLL', 'Recharge X-6'), ('RECHARGE_AFTER_REST', 'Recharge after a Short or Long rest'), ('RECHARGE_SPECIAL', 'Recharge Special')], help_text='How use of the action is limited, if at all.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='creatureactionattack',
            name='attack_type',
            field=models.CharField(choices=[('SPELL', 'Spell'), ('WEAPON', 'Weapon'), ('SAVING_THROW', 'Saving Throw')], help_text='Whether this is a Weapon, Spell, or Saving Throw attack.', max_length=20),
        ),
        migrations.RemoveField(
            model_name='creatureactionattack',
            name='damage_type',
        ),
        migrations.RemoveField(
            model_name='creatureactionattack',
            name='extra_damage_type',
        ),
        migrations.AddField(
            model_name='creatureactionattack',
            name='damage_type',
            field=models.ManyToManyField(help_text='What kind of damage this attack deals', related_name='+', to='api_v2.damagetype'),
        ),
        migrations.AddField(
            model_name='creatureactionattack',
            name='extra_damage_type',
            field=models.ManyToManyField(help_text='What kind of extra damage this attack deals', related_name='+', to='api_v2.damagetype'),
        ),
    ]
