# Generated by Django 5.2.1 on 2025-05-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0042_alter_creatureaction_uses_type_and_more'),
        ('api_v2', '0046_characterclass_primary_abilities_and_more'),
    ]

    operations = [
    ]
