# Generated by Django 5.2.1 on 2025-05-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0047_merge_20250531_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatureaction',
            name='uses_type',
            field=models.CharField(blank=True, choices=[('PER_DAY', 'X/Day'), ('RECHARGE_ON_ROLL', 'Recharge X-6'), ('RECHARGE_AFTER_REST', 'Recharge after a Short or Long rest'), ('RECHARGE_SPECIAL', 'Recharge Special'), ('PER_ROUND', 'X/Round'), ('RECHARGE_MINUTES', 'Recharge after X minutes'), ('PER_HOUR', 'X/Hour'), ('PER_WEEK', 'X/Week')], help_text='How use of the action is limited, if at all.', max_length=20, null=True),
        ),
    ]
